### ISSUE TITLE
Add filters to on_record_save function

### ISSUE THREAD

**Issue by davidsherlock** [audiotheme/audiotheme#57]
It would be useful if filters existed within the `on_record_save` function add additional fields to the save routine array. The exact line would be:

```
// Whitelisted fields.
$fields = array( 'release_year', 'artist', 'genre' );
```

I had an instance when I had to add record label and a few other variables and it would be useful to be able to add this via a filter.

**Comment by bradyvercher** [comment]
Thanks for the suggestion, @davidsherlock. I understand how that would be useful, but that loop is really just an implementation detail and isn't really meant to be a framework for saving external data. I'd expect sanitization rules and prefixes to be different for custom fields, so it's a bit rudimentary for saving custom data.

We also don't want to create potential conflicts by automatically prefixing custom fields with our own prefix. For instance, we might introduce a record label and catalog number field in the future.
