### ISSUE TITLE
Archive menu item duplication in WP Menus

### ISSUE THREAD

**Issue by lukemcdonald** [audiotheme/audiotheme#6]
The WP Menus Archive meta box gets duplicated menu options when importing data from another install that previously had AudioTheme activated. It might help to see the result by reproducing the steps below (multi-site install).
1. Create a new site
2. Activate the AudioTheme Framework Plugin
3. Import data from an AudioTheme demo; I used Americanuara's demo content ([file](http://d.pr/f/OhtK)).

You'll notice in the Archive meta box of Appearance > Menus there are six menu items:
- Videos
- Records
- Gigs
- Videos
- Music
- Shows

You'll also notice in the Primary menu, the Music, Shows, and Videos menu items will 404. This is because the slugs are indexed with a `-2` and point to archive pages that don't exist.

Hopefully that explanation makes some sort of sense. You should be able to reproduce the issue with the steps provided. If not, I'll double check the steps as I went of the top of my head.

**Comment by bradyvercher** [comment]
The `can_export` property for Archive post types was set to `false` awhile back, so this shouldn't be a problem anymore.

**Comment by muymoo** [comment]
@bradyvercher I have a fresh install of audiotheme but am seeing multiple (6x Gigs, Videos, Records) in the menu selection list. Where would I delete the duplicate archives?
