### ISSUE TITLE
Videos in Tag Archives

### ISSUE THREAD

**Issue by lukemcdonald** [audiotheme/audiotheme#9]
The video CPT uses the standard Tags taxonomy. If a video is tagged, it does not show in the tag archives. There are a few methods online about adding CPT's to the tags archive with `pre_get_posts`, however, I'm wondering if this can be done automatically via the Framework or if each theme will need to add this functionality individually.

**Comment by bradyvercher** [comment]
Post tag support was removed from videos in d39279b in favor of video categories. If anyone needs tag support, it should only take a couple lines of code to re-enable.
